# -*- coding: utf-8 -*-
"""Taxi-V3.ipynb

Automatically generated by Colaboratory.

"""

import gym
import random
import numpy as np
from time import sleep
from IPython.display import clear_output

env = gym.make("Taxi-v3")
env.reset()
tabela_q = np.zeros([env.observation_space.n, env.action_space.n])

epsodio = 20000
alpha = 0.1 # Taxa de aprendizado
gamma = 0.6 # Taxa de desconto
epsilon = 0.1 # Chance de selecionar uma ação aleatória em vez de maximizar a recompensa

for i in range(epsodio):
  feito = False
  penalidade, premiacao = 0,0
  estado = env.reset()
  while not feito:
    if random.uniform(0,1) < epsilon:
      acao = env.action_space.sample()
    else:
      acao = np.argmax(tabela_q[estado])

    if premiacao == -10:
      penalidade = 1

    proximo_estado, premiacao, feito, info = env.step(acao)
    exibir(acao, proximo_estado, premiacao, feito, info)

    valor = tabela_q[estado, acao]
    maior_valor = np.max(tabela_q[proximo_estado])

    novo_valor = (1 - alpha) * valor + alpha * (premiacao + gamma * maior_valor)
    tabela_q[estado, acao] = novo_valor

    estado = proximo_estado
  if i % 100 == 0:
    print("Penalidades: {}".format(penalidade))
    print("Epsisódio: {}".format(i))

def exibir (*args):
  clear_output(wait=True)
  if env is not None:
    env.render()

  if len(args) > 0:
    for arg in args:
      print(arg, end=" ")
    print("")
  sleep(0.3)
